PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>

SELECT ?note ?title ?created
WHERE {
  ?note dcterms:subject <https://ben.example/pim/tag-rdf> ;
        dcterms:title ?title ;
        dcterms:created ?created .
  FILTER(?created >= NOW() - "P30D"^^xsd:duration)
}
ORDER BY DESC(?created)
