name: Data Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.ttl'
      - 'shapes/**'
      - 'validate_pim.py'
      - '.github/workflows/validate.yml'
  push:
    branches: [ main ]
    paths:
      - '**.ttl'
      - 'shapes/**'
      - 'validate_pim.py'
      - '.github/workflows/validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: pim-rdf
        # Note: Using public cache, no auth token needed for reading
        
    - name: Install dependencies with Nix
      run: |
        nix-shell --run "echo 'Dependencies installed via nix-shell'"
        
    - name: Run SHACL validation
      run: |
        nix-shell --run "python3 validate_pim.py"
        
    - name: Check validation results
      run: |
        echo "✅ All validation steps completed successfully!"
        echo "Validation includes:"
        echo "- TTL syntax validation"  
        echo "- Data merging verification"
        echo "- SPARQL query testing"
        echo "- SHACL shapes validation"